services:
  yalp_backend:
    build:
      context: .
    image: ghcr.io/waffelmeister/yalp_backend:latest
    container_name: yalp_backend
    env_file:
      - .env
    environment:
      MONGO_ADDRESS: mongodb
    volumes:
      - ./data/yalp/logs:/usr/src/app/logging
    ports:
      - 3001:3001
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: <change_me>
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express
    container_name: mongodb_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: <change_me>
      ME_CONFIG_MONGODB_URL: mongodb://root:<change_me>@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
