swagger: '2.0'
basePath: '/'
info:
  title: 'express-openapi sample project'
  version: '3.0.0'
definitions:
  Error:
    additionalProperties: true
  User:
    properties:
      name:
        type: 'string'
      mail: 
        type: 'string'
      guid:
        type: 'string'
      courseGuids:
        type: 'array'
        items: 
          type: 'string'
    required:
      - 'name'
      - 'guid'
      - 'mail'
  Script:
    properties: 
      guid:
        type: 'string'
      name:
        type: 'string'
      cards:
        type: 'array'
        items: 
          $ref: '#/definitions/Card'
    required:
      - 'guid'
      - 'name'
      - 'courseGuid'
  Course:
    properties: 
      guid:
        type: 'string'
      name: 
        type: 'string'
      scripts:
        type: 'array'
        items: 
          $ref: '#/definitions/Script'
      userGuids: 
        type: 'array'
        items: 
          type: string
    required:
      - 'guid'
      - 'name'
      - 'users'
  Card:
    properties: 
      guid:
        type: 'string'
      front:
        type: 'string'
      back:
        type: 'string'
    required:
      - 'guid'
      - 'front'
paths: {}
tags:
  - description: 'Authenification'
    name: 'Login'